# -*- coding: utf-8 -*-
"""train_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qrCwPFoB-azLAYNitKtBxiF3T8_N0g01
"""

!pip install pandas numpy scikit-learn joblib

import pandas as pd
import numpy as np

from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder

from sklearn.linear_model import LinearRegression

from sklearn.ensemble import (
    RandomForestRegressor,
    GradientBoostingRegressor
)

from sklearn.model_selection import TimeSeriesSplit

from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

df = pd.read_csv("ml_dataset.csv")

print(df.shape)

df.head()

df["fecha"] = pd.to_datetime(df["fecha"])

columnas_eliminar = [
    "fecha",
    "fecha_creacion",
    "fecha_modificacion",
    "usuario_modificacion",
    "stock_disponible_cierre"
]

df = df.drop(
    columns=columnas_eliminar,
    errors="ignore"
)

target = "cantidad_vendida_total"

X = df.drop(columns=[target])

y = df[target]

categoricas = X.select_dtypes(
    include=["object", "string"]
).columns.tolist()

print(categoricas)

preprocessor = ColumnTransformer(
    transformers=[
        (
            "cat",
            OneHotEncoder(
                handle_unknown="ignore"
            ),
            categoricas
        )
    ],
    remainder="passthrough"
)

tscv = TimeSeriesSplit(
    n_splits=5
)

modelos = {
    "Linear Regression":
        LinearRegression(),

    "Random Forest":
        RandomForestRegressor(
            n_estimators=100,
            random_state=42
        ),

    "Gradient Boosting":
        GradientBoostingRegressor(
            n_estimators=100,
            learning_rate=0.1,
            max_depth=3,
            random_state=42
        )
}

resultados = []

for nombre, algoritmo in modelos.items():

    maes = []
    rmses = []
    r2s = []

    for train_idx, test_idx in tscv.split(X):

        X_train = X.iloc[train_idx]
        X_test = X.iloc[test_idx]

        y_train = y.iloc[train_idx]
        y_test = y.iloc[test_idx]

        modelo = Pipeline([
            (
                "preprocessor",
                preprocessor
            ),
            (
                "model",
                algoritmo
            )
        ])

        modelo.fit(
            X_train,
            y_train
        )

        pred = modelo.predict(X_test)

        maes.append(
            mean_absolute_error(
                y_test,
                pred
            )
        )

        rmses.append(
            np.sqrt(
                mean_squared_error(
                    y_test,
                    pred
                )
            )
        )

        r2s.append(
            r2_score(
                y_test,
                pred
            )
        )

    resultados.append([
        nombre,
        np.mean(maes),
        np.mean(rmses),
        np.mean(r2s)
    ])

resultado_df = pd.DataFrame(
    resultados,
    columns=[
        "Modelo",
        "MAE",
        "RMSE",
        "R2"
    ]
)

resultado_df.sort_values(
    "R2",
    ascending=False
)

from sklearn.ensemble import RandomForestRegressor

modelo_final = Pipeline([
    (
        "preprocessor",
        preprocessor
    ),
    (
        "model",
        RandomForestRegressor(
            n_estimators=300,
            max_depth=12,
            random_state=42,
            n_jobs=-1
        )
    )
])

modelo_final.fit(X, y)

print("Modelo final entrenado.")

import joblib

joblib.dump(
    modelo_final,
    "modelo_demanda.pkl"
)

print("PKL generado correctamente.")

from google.colab import files

files.download(
    "modelo_demanda.pkl"
)

feature_names = (
    modelo_final
    .named_steps["preprocessor"]
    .get_feature_names_out()
)

importancias = (
    modelo_final
    .named_steps["model"]
    .feature_importances_
)

fi = pd.DataFrame({
    "feature_name": feature_names,
    "importance_value": importancias
})

fi = fi.sort_values(
    "importance_value",
    ascending=False
).reset_index(drop=True)

fi["ranking"] = fi.index + 1

fi.head(20)

from datetime import datetime

fi["modelo_version"] = "RandomForest_v1"

fi["fecha_entrenamiento"] = datetime.now()

fi["usuario_ejecucion"] = (
    "02_train_model.ipynb"
)

fi.insert(
    0,
    "id_importance",
    range(
        1,
        len(fi)+1
    )
)

fi.to_csv(
    "ml_feature_importance.csv",
    index=False
)

print("Archivo generado.")

from google.colab import files

files.download(
    "ml_feature_importance.csv"
)

import pandas as pd
import joblib

modelo = joblib.load(
    "modelo_demanda.pkl"
)

print("Modelo cargado.")

score_df = pd.read_csv(
    "ml_score_input.csv"
)

print(score_df.shape)

score_df.head()

import pandas as pd
import numpy as np
import joblib

modelo = joblib.load(
    "modelo_demanda.pkl"
)

score_df = pd.read_csv(
    "ml_score_input.csv"
)

dim_producto = pd.read_csv(
    "dim_producto.csv"
)

print(score_df.shape)

score_model = score_df.copy()

score_model = score_model.rename(
    columns={
        "precio_unitario_estimado":
            "precio_unitario_promedio",

        "descuento_estimado":
            "descuento_total",

        "inversion_ads_planificada":
            "inversion_ads_total",

        "clics_estimados":
            "clics_total",

        "impresiones_estimadas":
            "impresiones_total",

        "temperatura_promedio_estimada":
            "temperatura_promedio_celsius",

        "temperatura_maxima_estimada":
            "temperatura_maxima_celsius",

        "humedad_porcentaje_estimada":
            "humedad_porcentaje",

        "precipitacion_mm_estimada":
            "precipitacion_mm"
    }
)

score_model["conversiones_total"] = 0
score_model["porcentaje_descuento_promedio"] = 0
score_model["stock_minimo"] = 0
score_model["riesgo_demanda_censurada"] = False